name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Save Terraform Plan Output if Failed
      if: steps.plan.outcome == 'failure'
      run: echo "${{ steps.plan.outputs.stdout }}" > plan.txt
    
    - name: Upload Terraform Plan Output
      if: steps.plan.outcome == 'failure'
      uses: actions/upload-artifact@v2
      with:
        name: plan
        path: plan.txt